### ISSUE TITLE
parsing error on packages with `git+`

### ISSUE THREAD

**Issue by Amar1729** [Amar1729/pip-rewind#2]
Dependency:
```
git+https://github.com/ge-semtk/semtk-python3@1b61fffa5557bb5c2f124394934a2e6bcef86538
```

Raises an unrecoverable error for pip-rewind. Investigate

```
Exception ignored in: <generator object requirements_parser at 0x7f6c8badceb0>
Traceback (most recent call last):
  File "/home/Amar1729/.local/lib/python3.8/site-packages/pip_rewind/cli.py", line 39, in main
    version = get_first_version_before(module, args.date)
RuntimeError: generator ignored GeneratorExit
Traceback (most recent call last):
  File "/home/Amar1729/.local/bin/pip-rewind", line 8, in <module>
    sys.exit(main())
  File "/home/Amar1729/.local/lib/python3.8/site-packages/pip_rewind/cli.py", line 39, in main
    version = get_first_version_before(module, args.date)
  File "/home/Amar1729/.local/lib/python3.8/site-packages/pip_rewind/versions.py", line 101, in get_first_version_before
    version = get_first_version_before_rss(pkg, date)
  File "/home/Amar1729/.local/lib/python3.8/site-packages/pip_rewind/versions.py", line 53, in get_first_version_before_rss
    for version, release_date in get_versions(pkg):
  File "/home/Amar1729/.local/lib/python3.8/site-packages/pip_rewind/versions.py", line 33, in get_versions
    feed = rss_parser.Parser(xml=xml.content).parse()
  File "/home/Amar1729/.local/lib/python3.8/site-packages/rss_parser/_parser.py", line 39, in parse
    "version": main_soup.rss.get("version"),
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Amar1729** [comment]
Looks like current RE will match `git`, and then attempt to look at a module named `git` on pypi

https://github.com/Amar1729/pip-rewind/blob/a335f5c2b836fa169f7037872dff4a2f7d26232d/pip_rewind/parser.py#L23

I could hardcode a check for `git+` but i think more robust might be stripping trailing comments and then asserting that the match result is equal to the original line?
